apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080     # 외부에서 접근 가능한 고정 포트 (30000-32767 범위 내)
  type: NodePort
